// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// home_range_cpp
List home_range_cpp(arma::cube data, List par, arma::mat locations, int resolution, int nSimulatedSteps, int nSimulatedRuns, bool optimization, bool verbose);
RcppExport SEXP _homeranger_home_range_cpp(SEXP dataSEXP, SEXP parSEXP, SEXP locationsSEXP, SEXP resolutionSEXP, SEXP nSimulatedStepsSEXP, SEXP nSimulatedRunsSEXP, SEXP optimizationSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube >::type data(dataSEXP);
    Rcpp::traits::input_parameter< List >::type par(parSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type locations(locationsSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    Rcpp::traits::input_parameter< int >::type nSimulatedSteps(nSimulatedStepsSEXP);
    Rcpp::traits::input_parameter< int >::type nSimulatedRuns(nSimulatedRunsSEXP);
    Rcpp::traits::input_parameter< bool >::type optimization(optimizationSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(home_range_cpp(data, par, locations, resolution, nSimulatedSteps, nSimulatedRuns, optimization, verbose));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_homeranger_home_range_cpp", (DL_FUNC) &_homeranger_home_range_cpp, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_homeranger(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
