#' Fit a home range model
#'
#' This is the main function that handles the
#' calibration of the home_range_cpp() C++ function
#' through hr_cost().
#'
#' @param data A data frame with driver data.
#' @param obs reference observations (path) to a track file generated by \{hr_xy()\}
#' @param par A list containing model calibration settings.
#' @param optim_out A logical indicating whether the function returns the raw
#'  output of the optimization functions (defaults to TRUE).
#' @param parallel support parallel processing
#' @param resolution resolution of the underlying maps (grid)
#' @param ... Optional arguments passed on to the cost function specified as
#'  \code{par$metric}.
#' @return A named list containing the calibrated parameter vector `par` and
#' the output object from the optimization `mod`. For more details on this
#' output and how to evaluate it, see \link[BayesianTools:runMCMC]{runMCMC} (also
#' \href{https://florianhartig.github.io/BayesianTools/articles/BayesianTools.html}{this post})
#' @export
#' @import BayesianTools

hr_fit <- function(
    data,
    obs,
    par,
    resolution,
    optim_out = TRUE,
    parallel = FALSE,
    ...
){

  # predefine variables for CRAN check compliance
  lower <- upper <- out_optim <- NULL

  # check input variables
  if(missing(obs) | missing(data) | missing(par)){
    cli::cli_abort("missing input arguments, please check all parameters")
  }

  # this routine allows for dynamic cost function
  # calling without too much trouble (consider deleting
  # if not really desired to limit overhead)
  cost <- function(settings, obs, data, resolution, names){
    eval(par$metric)(
      par = settings,
      obs = obs,
      data = data,
      resolution = resolution,
      names = names,
      ...
    )
  }

  # reformat parameters
  pars <- par_delist(par$par)

  priors  <- BayesianTools::createUniformPrior(
    unlist(pars$lower),
    unlist(pars$upper),
    unlist(pars$init)
  )

  # setup the Bayes run, no message forwarding is provided
  # so wrap the function in a do.call
  setup <- BayesianTools::createBayesianSetup(
    likelihood = function(random_par) {
      do.call("cost",
              list(
                settings = random_par,
                obs = obs,
                data = data,
                resolution = resolution,
                names = rownames(pars)
              )
            )
    },
    prior = priors,
    names = rownames(pars),
    parallel = parallel
  )

  # set bt control parameters
  bt_settings <- par$control$settings

  # calculate the runs
  cli::cli_alert_info("Fitting parameters...")
  out <- BayesianTools::runMCMC(
    bayesianSetup = setup,
    sampler = par$control$sampler,
    settings = bt_settings
  )

  # drop last value
  bt_par <- BayesianTools::MAP(out)$parametersMAP
  bt_par <- bt_par[1:(length(bt_par))]

  # calculate driver hash
  h <- rlang::hash(data)

  if(optim_out){
    out_optim <- list(
      par = bt_par,
      mod = out,
      hash = h
    )
  }else{
    out_optim <- list(
      par = bt_par,
      hash = h
    )
  }

  #print(out_optim$par)
  #names(out_optim$par) <- rownames(pars)
  return(out_optim)
}
