#' Fit a home range model
#'
#' This is the main function that handles the
#' calibration of the home_range_cpp() C++ function
#' through hr_cost().
#'
#' @param data A data frame with driver data.
#' @param obs reference observations (path) to a track file generated by \{hr_xy()\}
#' @param par A list containing model calibration settings.
#' @param optim_out A logical indicating whether the function returns the raw
#'  output of the optimization functions (defaults to TRUE).
#' @param parallel enable parallel processing (default = FALSE, if TRUE or the
#'  number of desired cores to use in processing).
#' @return A named list containing the calibrated parameter vector `par` and
#' the output object from the optimization `mod`. For more details on this
#' output and how to evaluate it, see \link[BayesianTools:runMCMC]{runMCMC} (also
#' \href{https://florianhartig.github.io/BayesianTools/articles/BayesianTools.html}{this post})
#' @export
#' @import BayesianTools

hr_fit <- function(
    data,
    obs,
    par,
    optim_out = TRUE,
    parallel = FALSE,
    verbose = FALSE
){

  # this routine allows for dynamic cost function
  # calling without too much trouble (consider deleting
  # if not really desired to limit overhead)
  cost <- function(settings, obs, data, resolution, names, cost_function){
   eval(parse(text = cost_function))(
     par = settings,
     obs = obs,
     data = data,
     resolution = resolution,
     names = names
   )
  }

  # define likelihood function setup
  ll <- function(X) {
    do.call("cost",
            list(
              settings = X,
              obs = obs,
              data = data$data,
              resolution = data$resolution,
              names = rownames(pars),
              cost_function = par$metric
            )
    )
  }

  # predefine variables for CRAN check compliance
  lower <- upper <- out_optim <- NULL

  # check input variables
  if(missing(obs) | missing(data) | missing(par)){
    cli::cli_abort("missing input arguments, please check all parameters")
  }

  if(parallel == TRUE || is.numeric(parallel)){

    # get max number of cores
    max_cores <- parallel::detectCores() - 1

    if(is.numeric(parallel)){
      n <- parallel
    } else {
      n <- max_cores
    }

    # feedback
    if(verbose){
      cli::cli_alert_info("Running optimization in parallel using {n} cores!")
    }

    # Create cluster with n cores
    cl <- parallel::makeCluster(n)

    # define parallel likelihood
    pll <- function(par){
      parallel::parApply(
        cl = cl,
        X = par,
        MARGIN = 1,
        FUN = ll
      )
    }

    # export functions / variables
    parallel::clusterExport(
      cl,
      varlist = list("ll","data","obs","cost", par$metric),
      envir = environment()
    )

    # flip parallel to external for cluster specific setup
    parallel <- "external"
  }

  # reformat parameters
  pars <- par_delist(par$par)

  priors  <- BayesianTools::createUniformPrior(
    unlist(pars$lower),
    unlist(pars$upper),
    unlist(pars$init)
  )

  # setup the Bayes run, no message forwarding is provided
  # so wrap the function in a do.call
  setup <- BayesianTools::createBayesianSetup(
    likelihood = if(parallel == "external"){pll}else{ll},
    prior = priors,
    names = rownames(pars),
    parallel = parallel
  )

  # set bt control parameters
  bt_settings <- par$control$settings

  if(parallel == "external"){
    # alter the settings to recognize the number of
    # cores / streams to process in parallel
    bt_settings$nrChains <- 1
    bt_settings$startValue <- setup$prior$sampler(n)
  }

  # calculate the runs
  invisible(
    capture.output(
      out <- suppressMessages(
        suppressWarnings(
          BayesianTools::runMCMC(
            bayesianSetup = setup,
            sampler = par$control$sampler,
            settings = bt_settings
          )
        )
      )
    )
  )

  # stop cluster
  if(parallel == "external"){
    parallel::stopCluster(cl)
  }

  # drop last value
  bt_par <- BayesianTools::MAP(out)$parametersMAP
  bt_par <- bt_par[1:(length(bt_par))]

  # calculate driver hash
  h <- rlang::hash(data)

  if(optim_out){
    out_optim <- list(
      par = bt_par,
      mod = out,
      hash = h
    )
  }else{
    out_optim <- list(
      par = bt_par,
      hash = h
    )
  }

  # print metadata if desired, helpful in debugging parallel setups
  if(verbose){
    cli::cli_alert("number of individuals: {length(unique(obs[,1]))}")
    cli::cli_alert("total number of positions: {nrow(obs)}")
    cli::cli_alert("number of chains: {length(out$chain)}")
    cli::cli_alert("chain length: {nrow(out$chain[[1]])}")
    cli::cli_alert(
      "runtime:
        user: {round(out$settings$runtime[1])}
        system: {round(out$settings$runtime[2], 1)}
        total: {round(out$settings$runtime[3])}
      "
    )
  }

  # return optimization output
  return(out_optim)
}
