#' Predict home range model values
#'
#' This is the main function to predict values from a fit set of
#' parameters.
#'
#' @param par model parameters
#' @param data A data frame with driver data.
#' @param obs reference observations (path) to a track file generated by \{hr_xy()\}
#' @param resolution resolution of the underlying maps (grid)
#' @param steps number of steps to simulate
#' @param runs number of runs to simulate
#' @param keep_start keep the starting position in the output data (this is
#'  run 0 and only has one coordinate, the release point)
#' @param optimization optimization trigger (only used in debugging, set to FALSE)
#' @param verbose provide feedback on the command line (default = TRUE)
#'
#' @returns simulated track
#' @export

hr_predict <- function(
  data,
  par,
  obs,
  resolution,
  steps = 1,
  runs = 1,
  keep_start = TRUE,
  optimization = FALSE,
  verbose = TRUE
){

  # remove coef names (only needed for regularization)
  # saves time as complex Rcpp/arma vector types are time expensive
  par$names <- NULL

  # call low level cpp model function
  output <- home_range_cpp(
    data = data,
    par = par,
    locations = obs,
    resolution = resolution,
    nSimulatedSteps = steps,
    nSimulatedRuns = runs,
    optimization = optimization,
    verbose = verbose
  )

  # if returning the log likelihood from an optimization
  # run return this early
  if (!optimization){

    # filter out the first run, i.e. the
    # starting position of the simulation
    if(!keep_start){
      output$locations <- output$locations |>
        dplyr::filter(.data$run != 0)
    }

    # set -9999 values to NA
    output$locations[output$locations == -9999] <- NA
    output$locations$id <- as.factor(output$locations$id)

    # class assignment
    class(output) <- c("hr_predict")
    return(output)

  } else {
    # set -9999 values to NA
    output$likelihood[output$likelihood == -9999] <- NA
    return(output)
  }
}
