# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

home_range_cpp <- function(data, par, trajectoryPath, resolution, nSimulatedSteps, nSimulatedRuns, optimization, verbose) {
    .Call(`_homeranger_home_range_cpp`, data, par, trajectoryPath, resolution, nSimulatedSteps, nSimulatedRuns, optimization, verbose)
}

