# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name home_range_cpp
#' @title Main home range estimation function
#' @description C++ back-end function doing all the heavy lifting
#' @param data data cube of the state space
#' @param par parameters for model execution or fitting
#' @param trajectoryPath location of the track file
#' @param resolution resolution (dimensions) of the state space (as not georeferenced)
#' @param nSimulatedSteps number of simulated steps to run
#' @param nSimulatedRuns number of runs to simulate
#' @param optimization return optimization outputs (TRUE or FALSE)
#' @param verbose provide verbose output (TRUE or FALSE)
#' @export
#'
#' @return simulated model locations or a target value for optimization
#'  (cost function)
NULL

home_range_cpp <- function(data, par, trajectoryPath, resolution, nSimulatedSteps, nSimulatedRuns, optimization, verbose) {
    .Call(`_homeranger_home_range_cpp`, data, par, trajectoryPath, resolution, nSimulatedSteps, nSimulatedRuns, optimization, verbose)
}

